[package]
name = "actuate"
version = "0.4.0-alpha.4"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A reactive user-interface framework"
repository = "https://github.com/actuate-rs/actuate"

[workspace]
members = [
    ".", "crates/actuate-winit",
    "crates/actuate-core",
    "crates/actuate-macros",
    "crates/actuate-winit"
]

[dependencies]
actuate-core = { version = "0.1.1", path = "crates/actuate-core" }
