[package]
name = "actuate"
version = "0.4.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A reactive user-interface framework"
repository = "https://github.com/actuate-rs/actuate"

[workspace]
members = [
    ".",
    "macros"
]

[dependencies]
actuate-macros = { version = "0.1.0", path = "macros" }
