[package]
name = "actuate"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A reactive runtime for embedded systems"
repository = "https://github.com/matthunz/actuate"

[features]
std = []
default = ["std"]

[dependencies]
hashbrown = "0.14.3"

[[example]]
name = "app"
required-features = ["std"]
